version: "3.0"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_PASSWORD: 1q2w3e4rQW!
      POSTGRES_USER: billing_user
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    restart: always

  billing_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=dev
      - PYTHONPATH=.
    depends_on:
      - postgres
      - redis
    container_name: billing_api

