"""create tables

Revision ID: 871ffc85aff2
Revises: 
Create Date: 2020-07-30 22:21:28.460705

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '871ffc85aff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('alias', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_currency_alias'), 'currency', ['alias'], unique=True, schema='public')
    op.create_table('reason',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_reason_code'), 'reason', ['code'], unique=True, schema='public')
    op.create_table('user',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_table('wallet',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(length=32), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_wallet_code'), 'wallet', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_wallet_user_id'), 'wallet', ['user_id'], unique=False, schema='public')
    op.create_table('operation',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('reason_id', sa.BigInteger(), nullable=False),
                    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
                    sa.Column('connected_wallet_id', sa.BigInteger(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('opdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['connected_wallet_id'], ['public.wallet.id'], ),
                    sa.ForeignKeyConstraint(['reason_id'], ['public.reason.id'], ),
                    sa.ForeignKeyConstraint(['wallet_id'], ['public.wallet.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_operation_connected_wallet_id'), 'operation', ['connected_wallet_id'], unique=False,
                    schema='public')
    op.create_index(op.f('ix_public_operation_opdate'), 'operation', ['opdate'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_reason_id'), 'operation', ['reason_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_wallet_id'), 'operation', ['wallet_id'], unique=False, schema='public')
    op.drop_table('alembic_version')
    op.drop_table('table_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_name',
                    sa.Column('column_1', sa.INTEGER(), autoincrement=False, nullable=True),
                    comment='sdfs'
                    )
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
                    )
    op.drop_index(op.f('ix_public_operation_wallet_id'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_reason_id'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_opdate'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_connected_wallet_id'), table_name='operation', schema='public')
    op.drop_table('operation', schema='public')
    op.drop_index(op.f('ix_public_wallet_user_id'), table_name='wallet', schema='public')
    op.drop_index(op.f('ix_public_wallet_code'), table_name='wallet', schema='public')
    op.drop_table('wallet', schema='public')
    op.drop_table('user', schema='public')
    op.drop_index(op.f('ix_public_reason_code'), table_name='reason', schema='public')
    op.drop_table('reason', schema='public')
    op.drop_index(op.f('ix_public_currency_alias'), table_name='currency', schema='public')
    op.drop_table('currency', schema='public')
    # ### end Alembic commands ###
