"""create tables

Revision ID: c50f37795990
Revises: 
Create Date: 2020-07-31 12:15:12.012556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50f37795990'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_currency_alias'), 'currency', ['alias'], unique=True, schema='public')
    op.create_table('reason',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_reason_code'), 'reason', ['code'], unique=True, schema='public')
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pasport_data', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasport_data'),
    schema='public'
    )
    op.create_table('wallet',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bill_number', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_wallet_bill_number'), 'wallet', ['bill_number'], unique=True, schema='public')
    op.create_index(op.f('ix_public_wallet_user_id'), 'wallet', ['user_id'], unique=False, schema='public')
    op.create_table('operation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('reason_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('connected_wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('opdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_wallet_id'], ['public.wallet.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['public.reason.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['public.wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_operation_connected_wallet_id'), 'operation', ['connected_wallet_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_opdate'), 'operation', ['opdate'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_reason_id'), 'operation', ['reason_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_wallet_id'), 'operation', ['wallet_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operation_correlation_id'), 'operation', ['correlation_id'], unique=True, schema='public')



def downgrade():
    op.drop_index(op.f('ix_public_operation_wallet_id'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_reason_id'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_opdate'), table_name='operation', schema='public')
    op.drop_index(op.f('ix_public_operation_connected_wallet_id'), table_name='operation', schema='public')
    op.drop_table('operation', schema='public')
    op.drop_index(op.f('ix_public_wallet_user_id'), table_name='wallet', schema='public')
    op.drop_index(op.f('ix_public_wallet_bill_number'), table_name='wallet', schema='public')
    op.drop_table('wallet', schema='public')
    op.drop_table('user', schema='public')
    op.drop_index(op.f('ix_public_reason_code'), table_name='reason', schema='public')
    op.drop_table('reason', schema='public')
    op.drop_index(op.f('ix_public_currency_alias'), table_name='currency', schema='public')
    op.drop_table('currency', schema='public')
    # ### end Alembic commands ###
